### ISSUE TITLE
[BUG] feature_id gets a 1 added to the end

### ISSUE THREAD

**Issue by hyperknot** [onthegomap/planetiler#1042]
**Describe the bug**
The OSM feature id gets a 1 to the end. For example:
471357231
https://www.openstreetmap.org/node/471357231 
is shown as 
<img width="240" alt="maputnik" src="https://github.com/user-attachments/assets/41178e97-70b5-4a3b-b570-074d207f54e8">

Latest full planet run, GitHub commit: cf49b86

**Comment by msbarry** [comment]
Yep that's the new behavior as of #826 - the feature ID is `osm ID * 10 + {1 for OSM nodes, 2 for OSM ways, 3 for OSM relations}` so you can tell whether the feature came from a node, way or relation.  You can set `--feature-source-id-multiplier=false` if you want to disable the behavior and just set vector tile feature IDs to the original ID of the osm element.

**Comment by hyperknot** [comment]
I see, thanks!
