### ISSUE TITLE
[FEATURE] Clarifying Java version and documentation

### ISSUE THREAD

**Issue by katrinayfmei** [onthegomap/planetiler#1058]
**Is your feature request related to a problem? Please describe.**
As a new developer I was following the Planetiler instructions. I came across the below requiring Java 22+, however all the main documentation says Java 21+. Clarifying if the documentation needs to be updated.
https://github.com/onthegomap/planetiler-examples

**Comment by msbarry** [comment]
Planetiler require java 21, but the planetiler-examples repo uses a new java capability they added in Java 22 to run java programs without a compile step which makes it simpler to write a new custom profile in Java without any build tools.

So with Java 21 you can:
- run planetiler using any of the built-in profiles (openmaptiles, QA tiles)
- run planetiler against a custom yaml schema
- compile a custom java program profile against java (maven, gradle, etc.)

But with Java 22 you can additionally run `java -jar planetiler.jar Profile.java` to run a custom java program without maven, gradle, etc.

The planetiler-examples repo explains that a little bit, which side do you think needs to be updated to make that more clear?

**Comment by katrinayfmei** [comment]
Hi Barry!

Thank you for explaining that makes much more sense now. After the explanation I do not think a doc update would be needed :)
