### ISSUE TITLE
[BUG] Buffer not applied to fully filled tiles

### ISSUE THREAD

**Issue by moodstubos** [onthegomap/planetiler#1098]
Hi,
First of all, thank you very much for this tool! It’s amazing!

I am currently using version 0.8.x with a custom `defaultBufferPixels` set to 15. This buffer is necessary for proper display in my project: the polygon has a thick outer line style, and without the correct buffer, this line also appears on inner tiles of the polygon.

**Issue found:** The buffer is not applied to the target tile when a polygon fully covers the entire tile. However, as soon as a polygon intersects the current tile, the buffer is correctly applied.

**To Reproduce**
example polygon + planetiler schema file
[bug_report.zip](https://github.com/user-attachments/files/17730387/bug_report.zip)

**Screenshots**
upper tile is correctly buffered. 
bottom tile has no included buffer.
![image](https://github.com/user-attachments/assets/9b996cac-f1d1-4819-8b40-38d8e2636fed)

**Environment:**
- OS: ubuntu122.04)
- Java version and distribution: openjdk 21.0.5 2024-10-15

**Comment by msbarry** [comment]
OK yes looks like this was an optimization that precomputes the "fill polygon" once and uses it across every filled polygon. I'll change that to create a fill polygon per polygon feature so that the fills respect the configured feature buffer size: #1100

**Comment by moodstubos** [comment]
you're awesome!

I confirm that the problem has been resolved. 
Thank you
