### ISSUE TITLE
[FEATURE] Consider Visvalingam-Whyatt algorithm for simplification

### ISSUE THREAD

**Issue by brawer** [onthegomap/planetiler#1105]
Looking at the Planetiler codebase, it seems that line simplification is currently done with the Douglas-Peucker algorithm. As an alternative, have you considered the [Visvalingam-Whyatt algorithm](https://en.wikipedia.org/wiki/Visvalingam%E2%80%93Whyatt_algorithm), which may give better-looking results? [Tilemaker](https://github.com/systemed/tilemaker) seems to be using Visvalingam-Whyatt through a [C++ library](https://github.com/felt/tippecanoe/blob/main/visvalingam.cpp) originally made for [Tippecanoe](https://github.com/felt/tippecanoe) inspired by a [Go implementation](https://github.com/paulmach/orb/blob/master/simplify/visvalingam.go), but there’s also a [Java function](https://github.com/metteo/jts/blob/master/jts-core/src/main/java/com/vividsolutions/jts/simplify/VWLineSimplifier.java) in JTS. See also [here](https://bost.ocks.org/mike/simplify/) and [here](https://www.jasondavies.com/simplify/) for interactive explanations of the algorithm, and the [original paper](https://hull-repository.worktribe.com/preview/376364/000870493786962263.pdf).

**Comment by msbarry** [comment]
Yes! That would be a great addition. The one issue with JTS library is that it should use a priority queue but instead does a [brute force approach](https://github.com/locationtech/jts/blob/9f0d2287a6cc0248932f0a790657ef20756b25ec/modules/core/src/main/java/org/locationtech/jts/simplify/VWLineSimplifier.java#L64) to find the next smallest triangle to remove, and probably has some other inefficiencies. It wouldn't be hard to implement an efficient version in planetiler though. That would also give us flexibility to use the effective area weighting function used on https://mapshaper.org

Beyond that it's mostly just a question of what the API should look like to switch between DP and VW. Could we specify "strategy=retain effective areas" and somehow transform the DP tolerance to a VW effective area limit?

See more discussion at https://github.com/onthegomap/planetiler/discussions/534 and https://github.com/onthegomap/planetiler/discussions/708

**Comment by msbarry** [comment]
Added Visvalingam Whyatt simplification option in #1109. You can opt-into it on a feature by using `feature.setSimplifyMethod(SimplifyMethod.RETAIN_EFFECTIVE_AREAS)` or `feature.setSimplifyMethod(SimplifyMethod.RETAIN_WEIGHTED_EFFECTIVE_AREAS)`.  By default "tolerance" gets squared and used as the minimum area threshold, so you need to tune tolerance up a bit in order to end up with similar output size as DP simplification.  The weighted version sharp corners as well.

I'll tackle the `GeometryPipeline` in a followup PR.
