### ISSUE TITLE
[FEATURE] Support zoom-levels higher than 14

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#128]
Planetiler currently limits the maximum zoom level to 14 since that was the highest needed for the OpenMapTiles port.  Other schemas may want to go higher though.  It should at least be possible to go to z15, and possibly z16.

**Comment by msbarry** [comment]
The main issue to resolve to go higher than z14 is how `TileCoord` packs z/x/y coordinates into a 32-bit integer:

https://github.com/onthegomap/planetiler/blob/04da2864a6a41f84a65b6618cf98fca018bfb57c/planetiler-core/src/main/java/com/onthegomap/planetiler/geo/TileCoord.java#L70-L80

So that the tile coordinate can be used as the most-significant 32-bits of the 64-bit long key that features get sorted by to group into tiles:

https://github.com/onthegomap/planetiler/blob/main/planetiler-core%2Fsrc%2Fmain%2Fjava%2Fcom%2Fonthegomap%2Fplanetiler%2Fcollection%2FFeatureGroup.java#L92-L97

It should be possible to pack z15 tile IDs into 32 bits since there are 1.4 billion tile IDs, but to go to z16 we'd need 33 bits (steal one bit from another part of the sort key) since there are 5.7 billion IDs.

**Comment by msbarry** [comment]
@ZeLonewolf what do you think about z15 vs. z16 as the upper limit for tile generation for "micro-mapped" features?

**Comment by ZeLonewolf** [comment]
> @ZeLonewolf what do you think about z15 vs. z16 as the upper limit for tile generation for "micro-mapped" features?

With regard to feature utility in a map, there are lots of features that don't make sense to display until very high zoom.  If I were rendering manhole covers for exmaple, I'd probably start them at z19 😁

Is there a technical reason why we wouldn't make the maximum zoom level user-configurable?  It's really just a trade-off between disk space and download tile size.

**Comment by msbarry** [comment]
> > @ZeLonewolf what do you think about z15 vs. z16 as the upper limit for tile generation for "micro-mapped" features?
> 
> 
> 
> With regard to feature utility in a map, there are lots of features that don't make sense to display until very high zoom.  If I were rendering manhole covers for example, I'd probably start them at z19 😁
> 
> 
> 
> Is there a technical reason why we wouldn't make the maximum zoom level user-configurable?  It's really just a trade-off between disk space and download tile size.
> 
> 

A few reasons to limit:

1) We're packing feature sort keys into 64 bits and tile id into a 32-bit integer now, which can fit z15 but to go to z16 or beyond we'd need to adjust. Not impossible but only want to do it if there's a strong use case
2) output mbtiles size is currently ~80gb, it would be 200-300gb for z15 and close to 1tb for z16 so it starts to get unwieldy
3) processing time goes up by similar multiples 

Since a client-side style can limit showing some feature until a higher zoom level, the only real benefit to generating higher zoom levels is to limit tile size of the max zoom level you generate. Currently with the openmaptiles config, the biggest z13 tile is 366kb but  a few z14 tiles get up to 1.8mb. If you include more detailed poi's/trees that might push 3-4mb.

So maybe the best way to guesstimate this is to make a schema with all the "micro" features you might want to include in openmaptiles, then generate z14 and collect some stats on the avg/max bytes used per layer per tile to know how far we'd need to push down the micro features to make tile sizes reasonable. 

My hunch is z15 would keep tiles under 1mb, and z16 would keep max zoom tiles comparable with the rest of the tiles (200-300kb max)

**Comment by ZeLonewolf** [comment]
I'd say z15 is the most important because of the openmaptiles plan to add that zoom level, while we don't have a specific use case for z16.
