### ISSUE TITLE
[BUG] OMT Basemap generates transportation_name entry for minor roads

### ISSUE THREAD

**Issue by boldtrn** [onthegomap/planetiler#144]
**Describe the bug**

Planetiler creates a transportation_name entry with a ref for minor roads. This differs to OMT. I have a style that shows road signs. It now shows road signs for hiking and cycling routes.

**To Reproduce**

1. Compare OMT tiles to Planetiler OMT.

For example:
https://www.openstreetmap.org/relation/2268453
https://www.openstreetmap.org/relation/1153402

**Expected behavior**

I don't think it's an issue that Planetiler does this. There are applications that want to show highway signs for cycle routes etc. At least I think we should document it. That way, I know what I am getting and can update my styles to consider this change.

**Screenshots**

OMT vs Planetiler:
![Screenshot 2022-03-23 at 08 45 57](https://user-images.githubusercontent.com/1553525/159649943-06a94671-6842-4d12-8de2-7ab0f3b4810d.png)
![Screenshot 2022-03-23 at 08 46 13](https://user-images.githubusercontent.com/1553525/159649950-c6d30d14-699d-4415-ba5c-33ebcd76fb54.png)

**Comment by wipfli** [comment]
Interesting, is it maybe that transportation_name should only create a feature if `name` is present?

**Comment by boldtrn** [comment]
I am actually not 100% sure what the base logic in OMT is to create the ref. I assume it has to be a road of `tertiary` or higher. If there is a ref attached to a road, showing a road sign is good, even though the road has no name.

Just to make sure: I think it's not an issue that Planetiler behaves like this, as I could imagine scenarios where people need this info. It slightly breaks OMT compatibility.

**Comment by wipfli** [comment]
@zelonewolf?

**Comment by msbarry** [comment]
I think I see the issue, it should only be ref tag from major networks, not minor ones.  Put out a fix for this and #145 in #148

**Comment by msbarry** [comment]
In #148 I'm making the default behavior match openmaptiles, but you can opt-into the old behavior with the `--transportation-name-minor-refs` flag.

**Comment by msbarry** [comment]
Fixed in #148
