### ISSUE TITLE
[BUG] Limit latin name extraction to valid language codes with no non-latin characters

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#146]
The most robust fix would be to limit the subkeys to those that would be valid BCP 47 codes, like xx and xx-YY and xx-YY-ZZZZ. But limiting it to the languages in the profile should work too.

I think the revised non-Latin detection code would still be worth pursuing regardless. With just the smaller fix you’re suggesting, there will be cases where an alternative language’s name is arbitrarily chosen just because of a “non-Latin” character.

_Originally posted by @1ec5 in https://github.com/onthegomap/planetiler/issues/86#issuecomment-1076573531_

**Comment by SomeoneElseOSM** [comment]
Just in case people aren't aware of it, I'll throw in the canonical example where "odd" language codes are used that are in some sense correct: https://www.openstreetmap.org/node/267762522 .  There name:en_GB and name:en_IE are used to show the different names used by different communities - the https://buseireann.ie/ bus that goes there definitely only has "Derry" and "Doire" on the front!

Whether this is something that this repository ought to worry about is a different question of course - I just thought it might be useful to mention one of the edge cases.

**Comment by 1ec5** [comment]
What makes `name:en_GB` and `name:en_IE` odd is not the country codes but rather the underscores. To the extent that name subkeys should be valid IETF language tags, these keys should be `name:en-GB` and `name:en-IE`, respectively.
