### ISSUE TITLE
[FEATURE] Deduplicate MBTiles output

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#167]
The biggest bottleneck during mbtiles writing is writing repeated ocean tiles:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/1480504/162418476-d018160b-b5b2-415a-8a9b-05ebb6193a58.png">

It's possible to reduce from ~15 minutes to ~9 minutes by using 2 separate mbtiles tables plus a view that adheres to mbtiles spec:

- tile -> blob ID
- blob ID -> blob data

This also reduces output mbtiles files size by 20%

**Comment by bbilger** [comment]
are you already working on this @msbarry ? Otherwise I'd open a PR in the next few days with a (possible) fix. I already have something working, I just need to polish it a bit.

**Comment by msbarry** [comment]
Thanks for reaching out @bbilger! I'm working through performance-related issues in this order: https://github.com/onthegomap/planetiler/projects/2 so was planning to do this at some point but hadn't started on it yet.  Feel free to submit a PR!

My initial thought for this was to set up a benchmark to profile mbtiles write and read performance and if the deduplicated format wasn't faster both for writes and for reads, then we'd likely want leave both formats in place so a caller can choose based on the tradeoffs.

A couple of random ideas I was thinking of trying:

1. encoding tile x/y/z as a single integer  like [TileCoord](https://github.com/onthegomap/planetiler/blob/891537e2bc43adba4439d8b233dce2b9abf5ce27/planetiler-core/src/main/java/com/onthegomap/planetiler/geo/TileCoord.java#L41-L81) does to see if that improves size/write/read performance
2. splitting into 2 tables: tile ID -> blob ID and blob ID -> data (I'm guessing this hurts read performance due to the 2 lookups)
3. splitting into 2 tables: tile ID -> blob and "repeated tiles" blob ID -> data, where the first table normally holds the full tile as blob data, but when it detects a small repeated tile, instead store a single byte that points to an ID in the "repeated tiles" table so the view would treat that single byte as an index in the "repeated tiles" table at read time (similar to [this approach](https://stackoverflow.com/questions/68684759/storage-optimizing-sqlite-blob-to-act-as-data-or-foreign-key))

If you're just interested in doing #2 that's fine, we might just need to be able to switch between the old and new behavior with a command-line option if reads are slower.

**Comment by bbilger** [comment]
Great, will open a PR for 2 in the following days.

I already implemented everything with a command-line switch because results are a mixed.

I mainly tested with Australia and results so far are
- mbtiles size is going down significantly from 2.9GiB to 1.7GiB
- there's only a tiny improvement in the time it takes to write the tiles (trying to come up with a benchmark)
- tile read times increase by ~15%

I haven't thought about encoding tiles in a single integer but I'd assume it would also hurt read performance. Will test this once done with 2.
