### ISSUE TITLE
Arbitrary processing logic for configurable planetiler tiles

### ISSUE THREAD

**Issue by ZeLonewolf** [onthegomap/planetiler#179]
Blocked by #160

In #160 we're adding support for a custom mbtiles output using a declarative configuration file.  This approach is limited to simple logic.  For more complex cases, we need more configuration complexity or perhaps a plugin capability.

For example, we need to support the following:

> From openmaptiles: at least stripping nonlatin characters from names (but that might be handled by separate code), computing building render height from `building:{height,min_height,level,min_level}` tags.

> For simple schemas you could decide to push all of that logic to client-side style expressions, but for people to adopt the config approach we need some extension point for flexibility.  To get past this issue for now while keeping the option open for later, we could just use `contantValue`/`tagValue` as shortcuts but be open to eventually having `value` that accepts more of an expression-like or embedded script syntax.

_Originally posted by @msbarry in https://github.com/onthegomap/planetiler/pull/160#discussion_r850261863_

**Comment by msbarry** [comment]
Here are a few examples of yaml config formats that support dynamic expressions:

- [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions)
- [Github Actions](https://docs.github.com/en/actions/learn-github-actions/expressions)
- [Google Cloud Workflows](https://cloud.google.com/workflows/docs/reference/syntax/expressions)
- [Puppet](https://puppet.com/docs/puppet/6/lang_expressions.html)
- [Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html)
- [Maplibre style expressions](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/) - static json, but they can be converted to inline expressions with something like [jamsession](https://github.com/mapbox/expression-jamsession)

**Comment by msbarry** [comment]
Google's common expression language is looking like a top contender - there's a solid java implementation: https://github.com/projectnessie/cel-java/
