### ISSUE TITLE
[FEATURE] config-based profiles

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#18]
Right now you need to write Java code to build a custom profile. It might be nice if you could also write a json or yaml file that defines the logic and config for the profile.

**Comment by ZeLonewolf** [comment]
I am actively working on this using a YAML-based configuration language.  Feel free to assign to me for tracking.

**Comment by wipfli** [comment]
@ZeLonewolf can you open a draft pull request with what you have at the moment? I am curious to see where this goes...

**Comment by ZeLonewolf** [comment]
> @ZeLonewolf can you open a draft pull request with what you have at the moment? I am curious to see where this goes...

I will do that as soon as I get the code into a non-broken state :)
