### ISSUE TITLE
Deterministic ordering of points with same sort order

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#215]
When 2 points have the same sort key, include the bytes when comparing them so that the ordering is deterministic.

_Originally posted by @nyurik in https://github.com/onthegomap/planetiler/discussions/214#discussioncomment-2697226_

**Comment by nyurik** [comment]
Technically this might not fully solve the issue. Osm allows two points to have identical coordinates (or they could get the same x,y during simplification). You might want to add tag sorting as the last fallback.

**Comment by bbilger** [comment]
Would you have some pointer for me where this sorting is happening currently? Then I'll take a look into this.
