### ISSUE TITLE
Possible to upload CI build artifacts

### ISSUE THREAD

**Issue by shermp** [onthegomap/planetiler#220]
Would it be possible to upload the CI build artifacts in the workflow?

It would be highly useful for non Java folks like me who want to test PR's without having to setup a build system to compile from source. Granted, I was able to use the openjdk docker image, so it wasn't too bad, but it would be very nice to be able to just download jar files.

And thank you so much for Planetiler. A week ago I thought I was stuck with the OpenMapTiles docker stack (and the abysmally slow tile generation). Then I discovered Tilemaker, and shortly thereafter planetiler. I would never have dreamed that I'd be able to generate New Zealand tiles in under 30 minutes on my old 4 core 8Gig linux box, let alone the whole `australia-oceania` region.

**Comment by msbarry** [comment]
Thanks! This is leftover from when planetiler was a private project and storage was limited, but I think it makes sense to publish these artifacts now. How long of a retention period do you think would be necessary?

**Comment by shermp** [comment]
Not too long. But from memory, I think github deletes artifacts older than 90 days anyway, so it probably doesn't matter if you don't clean them up. They're also only available to logged in GH users, so not available for general download.

**Comment by msbarry** [comment]
Sounds good, just addressed in #222 - the artifact should show up under "CI" check from a PR now.

**Comment by shermp** [comment]
Thank you very much for this.
