### ISSUE TITLE
[BUG] Elevations in feet are misinterpreted as meters

### ISSUE THREAD

**Issue by 1ec5** [onthegomap/planetiler#224]
When parsing an `ele` tag expressed in feet and inches, Planetiler discards the unit and interprets any number at the beginning of the value as a measurement in meters for the `ele` field, then converts it to feet for the `ele_ft` field. As a result, both fields are inaccurate. Instead, it should recognize that a value of the form `432'1"` is expressed in feet and inches, one of the established [unit specifications](https://wiki.openstreetmap.org/wiki/Map_features/Units) for OSM tags and convert it to meters as appropriate. This will enable more accurate labeling of peaks and other features primarily in the United States, as described in [this proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/ele_with_units).

https://github.com/onthegomap/planetiler/blob/9c1472fd30e4c84c8fc5d8a69fa8fd1c1aa08543/planetiler-basemap/src/main/java/com/onthegomap/planetiler/basemap/layers/MountainPeak.java#L115-L120 https://github.com/onthegomap/planetiler/blob/9c1472fd30e4c84c8fc5d8a69fa8fd1c1aa08543/planetiler-basemap/src/main/java/com/onthegomap/planetiler/basemap/util/Utils.java#L63-L66 https://github.com/onthegomap/planetiler/blob/9c1472fd30e4c84c8fc5d8a69fa8fd1c1aa08543/planetiler-core/src/main/java/com/onthegomap/planetiler/util/Parse.java#L14 https://github.com/onthegomap/planetiler/blob/9c1472fd30e4c84c8fc5d8a69fa8fd1c1aa08543/planetiler-basemap/src/main/java/com/onthegomap/planetiler/basemap/util/Utils.java#L52-L57

**Comment by msbarry** [comment]
@1ec5 thanks for pointing this out - I took a stab at a fix in #226 - let me know what you think!
