### ISSUE TITLE
[BUG] housenumber wrongly placed.

### ISSUE THREAD

**Issue by farfromrefug** [onthegomap/planetiler#237]
This is osm
<img width="253" alt="Screenshot 2022-05-29 at 17 28 53" src="https://user-images.githubusercontent.com/655344/170877510-de199b9b-705b-435d-8246-714d93bab5ec.png">

This is omt
<img width="529" alt="Screenshot 2022-05-29 at 17 25 32" src="https://user-images.githubusercontent.com/655344/170877359-9e8f0f4e-04ea-4549-b4d1-d73b91db4977.png">

This is PT
<img width="531" alt="Screenshot 2022-05-29 at 17 25 48" src="https://user-images.githubusercontent.com/655344/170877372-b06a1a16-1387-4f3b-a332-51ce88326798.png">

As you can see the housenumber is wrongly place in PT . And you actually end up not knowing on which side of the building it should be. I understand why it is there because of `centroidIfConvex`.

**Comment by msbarry** [comment]
Thanks for pointing this out - looks like `isConvex` is actually returning a result for `isConcave`.  I'll put out a quick fix for it.
