### ISSUE TITLE
[BUG] Min size and tolerance too small when using `--maxzoom` option

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#262]
Planetiler sets a tighter min size and tolerance at max zoom threshold to support overzooming, but it should instead let you change maxzoom without affecting the tiles that get emitted at each zoom.

![image](https://user-images.githubusercontent.com/1480504/172366557-50444421-4ccc-4090-a4a0-3373fdd33664.png)

https://osmus.slack.com/archives/C031V9E9RMG/p1654542711621759

**Comment by farfromrefug** [comment]
We can see this as the need for 2 kind of maxzoom:
* maxzoom related to maxzoom for simplification
* maxzoom like the maximum zoom to render 

I see 2 ways to fix this:
* replace `config.maxzoom()` in `FeatureCollector` with `MAX_ZOOM` static variable which is now fixed to 14
* create a second `maxzoom` configuration property. Maybe `maxRenderZoom`(or something) . In this case i dont know if we really need `minRenderZoom` or if `config.minzoom()` is used only for this.

The issue i see with the first one is the same issue as with `MAX_ZOOM` being hardcoded (related to https://github.com/onthegomap/planetiler/issues/128). What if you want a different value than 14?

**Comment by msbarry** [comment]
Fixed by #272
