### ISSUE TITLE
[FEATURE] Adding `-V/--version` flag to jar would be super nice! or how-do-i get the version if it is already avalible?

### ISSUE THREAD

**Issue by jessekrubin** [onthegomap/planetiler#326]
Adding a `-V`/`--version` cli flag would be super nice! 

Does it already exist in the cli? if so how do I get the current planetiler jar version?

**Comment by wipfli** [comment]
Thanks @jessekrubin for your interest in Planetiler. I think it would be easier to understand the issue if you put the question in the content of the issue and keep the title short...

**Comment by jessekrubin** [comment]
> Thanks @jessekrubin for your interest in Planetiler. I think it would be easier to understand the issue if you put the question in the content of the issue and keep the title short...

Done!
