### ISSUE TITLE
Mountain peak layer missing

### ISSUE THREAD

**Issue by clementmas** [onthegomap/planetiler#411]
The layer `mountain_peak` is missing from the [Planetiler Demo](https://onthegomap.github.io/planetiler-demo).

Is this layer not present in the generated tiles (anymore)? I've seen some commits related to this but it seems to be gone.

I'm going to generate the tiles but I want to make sure I can display the mountain peaks.

Thanks!

**Comment by phanecak-maptiler** [comment]
I believe `mountain_peak` layer is still present in output generated with planetiler's OpenMapTiles profile.
![Screenshot-Rysy](https://user-images.githubusercontent.com/115141505/209678812-1900d2a7-ac7c-4d0e-85bd-44bfcf130128.png)

**Comment by msbarry** [comment]
This demo uses data generated by @ZeLonewolf. I think he's using a docker image tag stuck at an old version. Brian, next time you generate can you use latest tag?

**Comment by ZeLonewolf** [comment]
If this is using the planet mbtiles hosted on my EFS share, I'm using the script here:
https://github.com/ZeLonewolf/planetiler-scripts/blob/main/03_render_planet.sh

How should I change it to use the latest tag?

**Comment by msbarry** [comment]
I think you should just be able to change `ghcr.io/onthegomap/planetiler:moveafter` to `ghcr.io/onthegomap/planetiler:latest`

**Comment by ZeLonewolf** [comment]
If this is using the planet mbtiles hosted on my EFS share, I'm using the script here:
https://github.com/ZeLonewolf/planetiler-scripts/blob/main/03_render_planet.sh

How should I change it to use the latest tag?

**Comment by msbarry** [comment]
OK I see the issue, it was actually just that the demo was missing a reference to the `mountain_peak` layer.  Added it here https://github.com/onthegomap/planetiler-demo/commit/49d43135543f40ce34c44d38f48ce488568d42db - should be all set now!
