### ISSUE TITLE
Run shortbread configurable schema on planet

### ISSUE THREAD

**Issue by wipfli** [onthegomap/planetiler#417]
How can I run the `shortbread.yml` configurable schema on the full planet? 

When I do something like `--area planet`, I get an error that geofabrik does now know this area.

Is hardcoding the planet download url like this the best solution?

```diff
   osm:
     type: osm
-    url: '${ args.osm_url }'
+    url: https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
```

**Comment by msbarry** [comment]
@wipfli you can use `--osm-url=aws:latest`, or we could change the schema to something like:

```diff
  osm_url:
    description: OSM URL to download
-    default: '${ "geofabrik:" + args.area }'1
+    default: '${ args.area == "planet" ? "aws:latest" : ("geofabrik:" + args.area) }'
```

?

**Comment by wipfli** [comment]
Sounds like a good idea to change the yaml file to do the if else logic. This also nicely shows the syntax of the inline expressions or however they are called...
