### ISSUE TITLE
[BUG] name:xx missing in transportation_name

### ISSUE THREAD

**Issue by ZeLonewolf** [onthegomap/planetiler#419]
Unblocks ZeLonewolf/openstreetmap-americana#618
CC @zstadler

Internationalized `name:xx` names are missing from roads in the transportation_name layer.

The following object show internationalized names in omt-tools:
![image](https://user-images.githubusercontent.com/3254090/208552068-ecbca63a-3ef4-4606-b968-0db0e334f1fe.png)

Same location in my planetiler server ([link](https://6ug7hetxl9.execute-api.us-east-2.amazonaws.com/data/v3/#14/32.08566/34.78968))
![image](https://user-images.githubusercontent.com/3254090/208553427-fb5d9511-18dc-45e3-9483-de2591843ae2.png)

**Comment by msbarry** [comment]
Good catch, looks like `transporation_name` layer does include all translations https://github.com/openmaptiles/openmaptiles/blob/c4d86d44a661146c273b97ac294db2381a570b2c/layers/transportation_name/transportation_name.yaml#L107 - can you transfer this to https://github.com/openmaptiles/planetiler-openmaptiles so we can fix over there?

I think the fix would just involve changing `OmtLanguageUtils.getNamesWithoutTranslations` to `OmtLanguageUtils.getNames` in `TransportationName.java`

**Comment by ZeLonewolf** [comment]
Done!  Moved to openmaptiles/planetiler-openmaptiles#58
