### ISSUE TITLE
[BUG] Vegetation squares

### ISSUE THREAD

**Issue by conotto** [onthegomap/planetiler#505]
Hi,
I noticed that both on https://onthegomap.com and demo https://onthegomap.github.io/planetiler-demo
vegetation shows up as square, as can be seen in the screenshot, can you please elaborate on why that is happening ?

<img width="1420" alt="Screenshot 2023-03-08 at 2 52 55 PM" src="https://user-images.githubusercontent.com/91792053/223834466-232297a5-28c7-434b-8992-73b019ecaa62.png">
<img width="1509" alt="Screenshot 2023-03-08 at 2 53 08 PM" src="https://user-images.githubusercontent.com/91792053/223834476-a57ad187-8700-4f2c-ad96-ea2faa506bb7.png">

**Comment by msbarry** [comment]
It looks like that's what the data is in OpenStreetMap: https://www.openstreetmap.org/#map=9/59.5343/-105.5594 - it's composed of a bunch of smaller "wood" regions (like [this](https://www.openstreetmap.org/relation/11130334)) but only within that square:

**Comment by conotto** [comment]
Thanks for your response.
Would overlaying vector data from https://www.naturalearthdata.com
Make it look prettier ?

**Comment by msbarry** [comment]
The openmaptiles profile (https://github.com/openmaptiles/planetiler-openmaptiles) uses natural earth to some extent at lower zoom levels, although there is no natural earth landcover vector source.  There is a natural earth raster source which is what onthegomap.com fades to at low zooms.

Maptiler has a vector landcover dataset that they use at low zooms: https://data.maptiler.com/downloads/dataset/landcover/#0.22/0/0 but it is closed-source. There's been some talk about making an open-source version from one of https://gisgeography.com/free-global-land-cover-land-use-data/ or https://www.usgs.gov/faqs/where-can-i-get-global-land-cover-data or even possibly by vectorizing low-zoom satellite images or natural earth raster data. But we don't have anything concerete yet. It's ripe for the taking if you want to work on it!

**Comment by erik** [comment]
I've gotten good results from vectorizing 500m satellite landcover data up to ~z9, but you'll need to do some post-processing smoothing to avoid a pixelated look.

MapTiler uses ESA Landcover for theirs (https://documentation.maptiler.com/hc/en-us/articles/4405446351889-Origin-of-the-MapTiler-Planet-data)

**Comment by conotto** [comment]
Thanks for the info guys, its clear now. Generating vector from satellite imagery is a bit over my head at the moment as i have no idea what that entails. If either of you have any helpful material to get started in that, i would appreciate it. I am willing to throw processing power at it but cannot commit much of manual labor to this task.

**Comment by msbarry** [comment]
Cool - out of curiosity what tools did you use for vectorizing @erik? I was thinking of ways to do it in planetiler directly but assume there are off-the-shelf tools that will do it too.

**Comment by conotto** [comment]
Over past couple of weeks ive been playing around and trying to get planet.osm.pbf and raster/vector naturalearth data converted to mbtiles. Played with GDAL, mb-util, tippecanoe, osmium, tilemaker and ofcourse planetiler.
Other than this my experience with mapping is rather limited.

**Comment by erik** [comment]
> Cool - out of curiosity what tools did you use for vectorizing @erik? I was thinking of ways to do it in planetiler directly but assume there are off-the-shelf tools that will do it too.

Basically just `gdal_sieve.py -> gdal_polygonize.py`. At 500m resolution the data is reasonably small, so nothing fancy needed. I did the smoothing in the Planetiler profile using [Chaikin's algorithm](https://www.cs.unc.edu/~dm/UNC/COMP258/LECTURES/Chaikins-Algorithm.pdf)

**Comment by conotto** [comment]
Please close this issue
