### ISSUE TITLE
[BUG] clipping creates incorrectly filled polygon geometry

### ISSUE THREAD

**Issue by erik** [onthegomap/planetiler#546]
Discovered a variant of #496 while investigating why a Dutch island was mysteriously disappearing at z6, but rendered fine on other levels.

https://user-images.githubusercontent.com/188935/229980662-5956801a-a83c-42d9-a743-24365ec86fc6.mov

The video is of @wipfli's map (it was the first public Planetiler source I could think of 😄), but the profile uses the same OSM water polygon source as my own, and exhibits exactly the same issue. [public map link](https://wipfli.github.io/swiss-map/#map=5.88/52.58/5.4)

The relevant portion of my profile is simple. There's no polygon merging or any other post processing:

```kotlin
    features.polygon("ocean")
      .setBufferPixels(4.0)
      .setMinZoom(6)
```

[swiss-map's implementation](https://github.com/wipfli/swiss-map/blob/main/planetiler/src/main/java/com/onthegomap/planetiler/examples/SwissMap.java#L268) is similarly simple.

I haven't dug into what exactly is happening, but looking at a tile inspector view, we can see the island is filled in (twice apparently, given the shading)

<img width="342" alt="image" src="https://user-images.githubusercontent.com/188935/229982804-e97354a1-0b27-4eff-9ca4-05b9fc0fc816.png">

Some quick changes I tried:

- Set `bufferPixels` to 0: no effect
- Set `bufferPixels` to 100: no effect
- Set `minPixelSize` to 0: no effect
- Set `pixelTolerance` to 0.5: **fixed**

[Here's the relevant WKT geometry](https://github.com/onthegomap/planetiler/files/11155150/problematic-ocean.wkt.zip).

**Comment by bdon** [comment]
Can you try making a minimum possible reproduction using an extract from https://app.protomaps.com/downloads/osm and share the OSM PBF + script to generate it here? 

Feels like this might be a cause where `buffer(0)` isn't robust enough.

**Comment by erik** [comment]
Did some more experimentation and was able to shrink it down to a couple test cases here https://github.com/erik/planetiler/commit/249f9b8d672b07d8b4285985b53c83a8b8df084f

The piers were a red herring. I think the problem is [from this south-western part](https://www.openstreetmap.org/#map=15/53.3465/5.1668) of the polygon 

Current understanding for z6, inside `FeatureRenderer`:

- `GeometryCoordinateSequences.reassemblePolygons(terschelling)` returns a geometry with a self-intersection in the inner ring. <details>![Screenshot 2023-04-13 at 22 10 11](https://user-images.githubusercontent.com/188935/231954181-1aaf0fad-a109-4b07-91fc-ce1738bf4f22.png) ![Screenshot 2023-04-13 at 22 10 15](https://user-images.githubusercontent.com/188935/231954176-f39db752-8c88-4466-a694-92bbb5561b7a.png)</details>
- `GeoUtils.snapAndFixPolygon()` fixes this self-intersection, but does so by filling the inner ring and returning a geometry that is not topologically valid (multipolygon with nested rings) <details> ![Screenshot 2023-04-13 at 22 09 47](https://user-images.githubusercontent.com/188935/231954356-e84a92e7-9a91-4713-a700-973620779936.png) ![Screenshot 2023-04-13 at 22 09 40](https://user-images.githubusercontent.com/188935/231954360-a2afd0a0-1b86-4d12-b31b-ac12ea6b8db1.png)</details>

**Comment by msbarry** [comment]
Thanks for digging into this @erik - I'm seeing the same thing.  The foolproof solution here would be to fix the polygon before calling snapAndFix (so I guess it would become fixAndSnap) - but in general the approach in planetiler has been to optimistically try working with the geometry first, detect if an invalid polygon causes an issue, then fail and fix it if so.  JTS precision reducer already detects and fails on most of the failure cases - Do you think there's an easy way to detect if this case has occurred? Either in planetiler, or we could make a change deeper within JTS as well.

**Comment by msbarry** [comment]
Here's an even more minimal test case:

```
POLYGON(
  (
    0 0,
    2 0,
    2 1,
    0 1,
    0 0
  ),
  (
    1.19053596444428 0.9029693332377,
    1.06439281777784 0.92184484124482,
    1.42787640888855 0.8257737683016,
    0.94579086222257 0.5617504680322,
    1.19053596444428 0.9029693332377
  )
)
```

Before:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/1480504/232045657-a193e6cd-fe6c-44f2-94ab-f999c7a57d30.png">

After:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1480504/232045843-3540415f-6ced-4e4b-a579-ac3fe4a903fb.png">

**Comment by msbarry** [comment]
Funny thing is if you do a pointwise precision reduction the output ends up valid

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1480504/232047230-1f65fee0-c546-4136-aadd-3fff47bce874.png">

**Comment by msbarry** [comment]
Looks like an issue might be that `Orientation.isCCW` returns true for that inner ring (before snapping) so JTS OverlayNG inverts it.  If JTS used `Orientation.isCCWArea` then the output would be what we expect.  The call chain is:

```
	  at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.computeDepthDelta(EdgeNodingBuilder.java:364)
	  at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.addPolygonRing(EdgeNodingBuilder.java:291)
	  at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.addPolygon(EdgeNodingBuilder.java:256)
	  at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.add(EdgeNodingBuilder.java:224)
	  at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.build(EdgeNodingBuilder.java:163)
	  at org.locationtech.jts.operation.overlayng.OverlayNG.nodeEdges(OverlayNG.java:541)
	  at org.locationtech.jts.operation.overlayng.OverlayNG.computeEdgeOverlay(OverlayNG.java:495)
	  at org.locationtech.jts.operation.overlayng.OverlayNG.getResult(OverlayNG.java:483)
	  at org.locationtech.jts.operation.overlayng.PrecisionReducer.reducePrecision(PrecisionReducer.java:62)
	  at org.locationtech.jts.precision.PrecisionReducerTransformer.reduceArea(PrecisionReducerTransformer.java:120)
	  at org.locationtech.jts.precision.PrecisionReducerTransformer.transformPolygon(PrecisionReducerTransformer.java:112)
	  at org.locationtech.jts.geom.util.GeometryTransformer.transform(GeometryTransformer.java:129)
	  at org.locationtech.jts.precision.PrecisionReducerTransformer.reduce(PrecisionReducerTransformer.java:41)
	  at org.locationtech.jts.precision.GeometryPrecisionReducer.reduce(GeometryPrecisionReducer.java:195)
	  at org.locationtech.jts.precision.GeometryPrecisionReducer.reduce(GeometryPrecisionReducer.java:83)
	  at com.onthegomap.planetiler.geo.GeoUtils.snapAndFixPolygon(GeoUtils.java:310)
```

**Comment by msbarry** [comment]
Opened up an issue against JTS: https://github.com/locationtech/jts/issues/974

**Comment by msbarry** [comment]
OK so it looks like this won't make it into JTS - our options are from fastest but least safe to slowest but most safe:

1. Override `EdgeNodingBuilder` in planetiler and change that one line to use `isCCWArea`
2. Change `snapAndFixPolygon`  to do an `isValid` check then `fix` if not before calling GeometryPrecisionReducer
3. Change  `FeatureRenderer` to do that same check immediately after simplifying geometries

I should run a quick check on the planet, but here are some stats testing on an r7g.metal instance on the planet:

| option | ocean time | osm pass2 time |  fixes this issue | prevents future GeometryPrecisionReducer issues | might prevent future SlicedGeometry issues |
| -- | -- | -- | -- | -- | -- |
| baseline | 32s | 12m29s | ⛔  | ? | ? |
| 1 | 31s | 11m51s | ✅  | ?  | ? |
| 2 | 34s | 13m58s | ✅  | ✅  | ? |
| 3 | 2m24s | 17m53s | ✅  | ✅  | ✅ |

It looks like `isCCWArea` is a little faster (and more appropriate for snapping to a grid IMO).  Verifying if a polygon is valid and fixing it can get expensive for individual very complex polygons which is why doing it in snapAndFix is faster - since the size and complexity of the polygon is limited since it's already clipped to a tile boundary.

WDYT?

**Comment by erik** [comment]
Since the issue seems really uncommon, I'd lean toward using one of the faster, less comprehensive fixes if possible.

Would it be feasible to collect some numbers on how many times each option catches a polygon that would be broken today? It's possible that there are more existing cases we don't know about because they're not as obvious as Terschelling.

**Comment by msbarry** [comment]
One interesting observation on #566 is that if I run over massachusetts the old logic fixed geometries after `snapAndFix` failed 2,629 times, but the new logic fixes geometries after isValid fails 20,945 times - so GeometryPrecisionReducer was doing quite a bit of fixing on its own.  I'm kind of surprised that we even need to fix the geometry separately because under the covers GeometryPrecisionReducer and geometry fixer are both just calling overlayng.

**Comment by bdon** [comment]
@msbarry no - I don't use [clipper2](http://www.angusj.com/clipper2/Docs/Overview.htm) at all, I use [clipper 1](http://www.angusj.com/delphi/clipper/documentation/Docs/Overview/_Body.htm) but 100% of polygons go through another step with [wagyu](https://github.com/mapbox/wagyu) ; wagyu guarantees simple and valid output with 0 exceptions I've encountered.
