### ISSUE TITLE
[FEATURE] Adjustment to ShapefileReader 

### ISSUE THREAD

**Issue by jbellander** [onthegomap/planetiler#559]
**Is your feature request related to a problem? Please describe.**
I'm using the shape file linked below. But the reader as it is now does not accept the file as ShapefileReader currently is implemented.

https://geodata.naturvardsverket.se/nedladdning/friluftsliv/Anordningar_shp.zip

Just as FYI that shape originates from Sweden's Environmental Protection Agencys open data.

**Describe the solution you'd like**
ShapefileReader:56 changed from `transformToLatLon = CRS.findMathTransform(src, dest);` to `transformToLatLon = CRS.findMathTransform(src, dest, true);` solves the issue. However not everyone will want to have it this so and option is probably needed.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by msbarry** [comment]
Ahh I was getting mixed up with `CRS.decode(projection, longitudeFirst);`

I'd like to move the sources to accept individual arguments like `source.shp?lenient=true&projection=EPSG:3857` but that's not quite supported yet.

What do you think in the meantime what if we log a warning in this case and retry with lenient=true? So at least it will accept the input but let you know there might be issues?

**Comment by jbellander** [comment]
I understand. But doing it as a fallback with a warning would be a simple solution that would work fine for my purposes. Nice!
