### ISSUE TITLE
[BUG] output doesn't work as expected

### ISSUE THREAD

**Issue by HeikoGr** [onthegomap/planetiler#560]
**Describe the bug**
i want to write pmtiles, but planetiler doesn't write the specified output file

**To Reproduce**
neither `docker run -e JAVA_TOOL_OPTIONS="-Xmx4g" -d -v "$(pwd)/data":/data [ghcr.io/onthegomap/planetiler:release](http://ghcr.io/onthegomap/planetiler:release) --download --area=monaco --maxzoom=12 --output=monaco.pmtiles --force` (release)
nor `docker run -e JAVA_TOOL_OPTIONS="-Xmx4g" -d -v "$(pwd)/data":/data [ghcr.io/onthegomap/planetiler:latest](http://ghcr.io/onthegomap/planetiler:latest) --download --area=monaco --maxzoom=12 --output=monaco.pmtiles --force` (latest)

doesn't write an output file.
i also tried `--output=monaco.mbtiles` without success.

it's only working without the output command (file written: output.mbtiles in data folder).

`--output-format=pmtiles` didn't help either.

**Expected behavior**
i expected an pmtiles file.

**Environment (please complete the following information):**

- Hardware: kvm virtualized with 4 cores and 16 gb ram
- OS: Debian Bullseye
- Java version and distribution: from docker

**Comment by msbarry** [comment]
Just to confirm are you running:

```
docker run -e JAVA_TOOL_OPTIONS="-Xmx4g" -d -v "$(pwd)/data":/data ghcr.io/onthegomap/planetiler:latest --download --area=monaco --maxzoom=12 --output=monaco.pmtiles --force
```

**Comment by HeikoGr** [comment]
yes

**Comment by msbarry** [comment]
try:

```
docker run -e JAVA_TOOL_OPTIONS="-Xmx4g" -d -v "$(pwd)/data":/data ghcr.io/onthegomap/planetiler:latest --download --area=monaco --maxzoom=12 --output=/data/monaco.pmtiles --force
```

That will put your output into `/data` which is mapped to your local `./data` directory - otherwise the output exists in the container but not your host machine.

**Comment by HeikoGr** [comment]
it works. thank you!

**Comment by HarelM** [comment]
I've encountered this issue as well, can the readme be updated to reflect this common scenario?

**Comment by wipfli** [comment]
Pull requests are welcome...
