### ISSUE TITLE
[BUG] Broken geometry of admin_level=4 boundary

### ISSUE THREAD

**Issue by tmshv** [onthegomap/planetiler#565]
Planetiler produces strange circle geometry from Kazakhstan boundary (Kyzylorda Province) at `z4`. Can be found at this location: `4.5/46.07/63.24`

**Screenshots**
<img width="608" alt="image" src="https://user-images.githubusercontent.com/290948/234236762-3dbf6a0f-ab46-422b-bafa-3ccb45d5778f.png">

**Comment by bdon** [comment]
This is part of the underlying [Natural Earth](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) dataset which displays the [Baikonur Cosmodrome](https://en.wikipedia.org/wiki/Baikonur_Cosmodrome) as its own admin-0 geometry. If you want a different display you can provide a modified input dataset.

**Comment by msbarry** [comment]
There's also a `--boundary-osm-only` command line flag you can use that tells openmaptiles profile to only use boundaries from openstreetmap at low zooms, not natural earth.

**Comment by tmshv** [comment]
Thanks!
