### ISSUE TITLE
[FEATURE] Fail fast when running planetiler with insufficient memory/storage

### ISSUE THREAD

**Issue by ZeLonewolf** [onthegomap/planetiler#70]
**Is your feature request related to a problem? Please describe.**
If a planetiler render is launched with insufficient memory or disk space, the build will run until memory/disk is exhausted.  However, this could be an hour or more before the limit is encountered, resulting in wasted time and an unclear error message to users (typically some type of out of memory error).

**Describe the solution you'd like**
Planetiler should note the size of the input file, and if it calculates that memory or disk space is insufficient to run to completion, it should fail quickly with an error message indicating the need for more disk space or memory.

**Comment by msbarry** [comment]
Good idea, I'm thinking checks at these points:
- [ ] Disk space before downloading data sources
- [ ] Disk space for node map (when using mmap), intermediate features, and mbtiles (ask profile for estimate)
- [ ] JVM memory available for node map (when using ram), and in memory data stores required by OsmReader, and profile
- [ ] Maybe warn when free memory on machine is < node map when using mmap

I wonder if it would also make sense to provide scripts with recommended settings to run for an extract vs. full planet from source/latest jar with Java/with docker.

**Comment by ZeLonewolf** [comment]
> I wonder if it would also make sense to provide scripts with recommended settings to run for an extract vs. full planet from source/latest jar with Java/with docker.

Yes - this was not clear from the docs when I ran the planet (thanks for the assist!)
