### ISSUE TITLE
[BUG] At zoom >= 5 I see nothing

### ISSUE THREAD

**Issue by dzfranklin** [onthegomap/planetiler#8]
**Describe the bug**
At zoom level at and above 5 I see no features.

**To Reproduce**
1. Visit https://onthegomap.github.io/flatmap-demo/#5/40.75/-108.36

**Expected behavior**
I see something similar to what I see at https://onthegomap.github.io/flatmap-demo/#4.9/40.75/-108.36

**Screenshots**
This is what I see when I follow the to reproduce steps:

![Screenshot_20211025-211245](https://user-images.githubusercontent.com/10361846/138802795-47639876-7b15-409c-bf44-aefd2c41d2f3.png)

**Environment (please complete the following information):**
 - Hardware: Moto One 5G Ace
 - OS: Android 10 (build QZKS30.Q4-40-95-2)
 - Java version and distribution: n/a
 - Maven version: n/a

**Additional context**
I can reproduce in mobile Firefox and mobile Chrome. I haven't tested anything else.

**Comment by msbarry** [comment]
Oops, I didn't have my notifications configured right and missed this issue at first. I tried to keep the data stored in the github pages repo below the 1GB limit so there's just a small subset in there.  I added a note to the demo when you're out of bounds to a bit more clear.
