### ISSUE TITLE
[BUG] data missing for quickstart

### ISSUE THREAD

**Issue by wipfli** [onthegomap/planetiler#90]
**Describe the bug**

The `quickstart-from-source.sh` script does not download data.

**To Reproduce**

1. clone this repo
2. configure java and intellij according to contributing guidelines
3. run `./quickstart-from-source.sh`
4. Error `Exception in thread "main" java.lang.IllegalArgumentException: data/sources/lake_centerline.shp.zip does not exist`

**Expected behavior**
`quickstart-from-souce.sh` should download the required assets.

**Environment (please complete the following information):**

- Hardware: dell xps 2021
- OS: ubuntu
- Java version and distribution: java 17.0.1 2021-10-19 LTS

**Comment by wipfli** [comment]
Maybe we could add instructions somewhere that one needs to download the stuff first with something like:

```
sudo docker run -e JAVA_TOOL_OPTIONS="-Xmx1g" -v "$(pwd)/data":/data ghcr.io/onthegomap/planetiler:latest --only-download --area=monaco
```

**Comment by msbarry** [comment]
Good catch! We'll add some more scripts for different run variations (docker/jar/maven) in #74 but for now I think all that might be needed is adding the `--download` option here
