### ISSUE TITLE
[BUG] Live demo tiles returning 403

### ISSUE THREAD

**Issue by danwiltshire** [onthegomap/planetiler#912]
**Describe the bug**
The Live Demo URL in the repo README.md isn't working - tiles are returning 403.

**To Reproduce**

1. Visit https://onthegomap.github.io/planetiler-demo/

**Comment by msbarry** [comment]
Updated with the new tile URL: https://github.com/onthegomap/planetiler-demo/commit/933f1884e95eb377eee7a9a49d93f0ed2f6c031c - @ZeLonewolf let me know if there's anything else I'll need to do to keep up with the transition of tile hosting to OSMUS?

**Comment by ZeLonewolf** [comment]
Hopefully not :sweat_smile:

The only thing left on this transition is the domain ownership transfer which should hopefully be transparent.
