### ISSUE TITLE
[FEATURE]  PMTiles output format

### ISSUE THREAD

**Issue by wipfli** [onthegomap/planetiler#98]
**Is your feature request related to a problem? Please describe.**

Currently, Planetiler outputs mbtiles which requires a tileserver, i.e., static file hosting like on github pages is not enough to serve tiles.

**Describe the solution you'd like**

[PMTiles](https://github.com/protomaps/PMTiles) can be used to serve vector tiles with range requests and they don't require a tile server. Planetiler could implement a pmtiles writer.

**Describe alternatives you've considered**

@bdon created a mbtiles to pmtiles converter:

```
pip install pmtiles
pmtiles-convert TILES.mbtiles TILES.pmtiles
```

**Additional context**
the powerlines example uses pmtiles https://github.com/wipfli/powerlines-switzerland

**Comment by msbarry** [comment]
I think this makes sense, probably migrate the `--mbtiles=output.mbtiles` option to `--output=output.mbtiles` or `--output=output.pmtiles` and switch the writer implementation based on file type. It sounds like the format is pretty straightforward, but Brandon pointed out that it would be beneficial to change the tiles order to collocate nearby tiles. He recommended hilbert curve order, but tile pyramid order might satisfy a similar goal and be a bit easier to implement?

**Comment by bdon** [comment]
Would it make sense to structure this as a separate Java library? If so, can that live alongside the python/js implementations at https://github.com/protomaps/PMTiles or should it live in its own Git repository?

**Comment by msbarry** [comment]
@bdon a separate library would be nice, then the wrapper in planetiler would be pretty minimal.  At the simplest it would need an API like:

```
try (var pmtiles = new PMTiles(file)) {
  for (var tile : tiles) {
    pmtiles.writeTile(tile.x, tile.y, tile.z, tile.data);
  }
} // close() flushes the index leaves
```

But for performance optimizations it might make sense to expose the hashing function and an API to write a tile with a known hash as well so the writer could avoid hashing the same bytes over and over again.

**Comment by msbarry** [comment]
Also @bdon could you elaborate on the tile ordering optimization? Is the main reason to put nearby tiles into the same index leaves? Planetiler packs tile x/y/z coordinates into a 32 bit integer that defines the order in which tiles are emitted, so I'd have to express a different ordering strategy as a different mapping from x/y/z to int.

**Comment by bdon** [comment]
The tile ordering refers to the order of the tiles in the archive; as of spec v2 their entries in the index is strictly defined (ascending z/x/y). If tiles are in Hilbert order in the archive, they are guaranteed to be nearby in the file if they're nearby in 2D - this locality makes a big latency difference if you're serving from disk and the OS is paging, but usually doesn't make a difference for cloud storage (depends on how it's implemented).

**Comment by msbarry** [comment]
I also found that writing pmtiles output is substantially faster (3 minutes for the planet), so I'm going to include a first pass of this in my "reducing single-threaded bottlenecks" workstream.  I'll write a pmtiles class with the goal of eventually extracting it to https://github.com/protomaps/PMTiles.

**Comment by msbarry** [comment]
Talking with @bdon, the pmtiles format is going through a couple of iterations between now and August so let's wait to add native pmtiles output until after that solidifies more.  @bdon feel free to ping this issue when you think the spec is in a stable state to build against.

**Comment by wipfli** [comment]
@bdon would it be possible to you the go-pmtiles implementation here in Java in Planetiler?

**Comment by wipfli** [comment]
I run Planetiler on the Shortbread configurable schema on the full planet. I created something like a 68 GB output file. Then I converted the .mbtiles to .pmtiles (25 minutes) and now I am uploading the file to R2 (roughly 30 minutes).

What would be amazing is if Planetiler could directly produce PMTiles and stream them to a S3-compatible storage provider...

**Comment by bdon** [comment]
> @bdon would it be possible to use the go-pmtiles implementation here in Java in Planetiler?

The plan is to output the PMTiles v3 format directly in the java code. It's on my plate, but need to finish up the Tippecanoe output first :)

**Comment by hallahan** [comment]
This is cool to see. What is the status? Almost done?

**Comment by wipfli** [comment]
I am really looking forward to #502.

Is it possible with `rclone` or something to upload the pmtiles file to an S3-compatible storage while planetiler is still writing?

**Comment by msbarry** [comment]
The pmtiles writer is going to write the whole file sequentially, then when it finishes it will go back to the beginning and write the header. I'm not sure if that pattern would work integrating with a third-party upload tool?

Theoretically I think planetiler could do the upload directly using the S3 multi-part upload API - it would just write the first part last once it knows what the first 127 byte header will be.

At the very least, #502 should combine your first 2 steps into one step that takes less than 15 minutes.

**Comment by bdon** [comment]
It should be simple to run planetiler and rclone in sequence to perform the upload.

My thought for the next v4 spec of pmtiles (backwards compatible, don't worry) is to allow for the header and root directories to be at the end of the archive. This would make the entire format streamable, meaning planetiler could write to storage as it's assembling the tiles, saving time and local disk space. 

To make this work however, we need to validate that every storage platform pmtiles v3 runs on supports end-addressing HTTP range requests correctly.

However, what @msbarry said about multipart uploads out-of-order would be even better and not require a spec revision. I'm not sure if that multipart behavior is consistent across storage platforms though.

**Comment by msbarry** [comment]
Resolved by #502

**Comment by wipfli** [comment]
Amazing, I need to try it out. Thanks @bdon for writing it and thanks @msbarry for the review!

**Comment by laurentdiazfr** [comment]
Thanks a lot for this. Can we use the command line to generate PMTILES ?

**Comment by msbarry** [comment]
Almost... I'm working on a change now so you can say `--output=result.pmtiles` to use the new functionality. Should be ready in a day or two.

**Comment by wipfli** [comment]
I did a comparison between the direct pmtiles writer in planetiler and the mbtiles writer + conversion afterwards to pmtiles. I did a planet run with my custom map tileset https://github.com/wipfli/swiss-map. Here is the result:

* New pmtiles writer total duration: 9146 seconds
* Previous mbtiles writer followed by conversion to pmtiles: 9171 seconds

This is on a 12 core, 128 GB machine. The logs are available here: https://gist.github.com/wipfli/17bb8ad8d123f7d93313417dc7d4fac5

It is surprising that the new pmtiles writer does not outperform the old way significantly. Did I somehow mess up some settings?

**Comment by wipfli** [comment]
Nice thanks!

**Comment by sing78** [comment]
Hi,one question:
I am running this command to generate pmtiles:

sudo java -Xmx1g -jar planetiler.jar --download --area=monaco --output=monaco.pmtiles

However,no monaco.pmtiles file is being created inside data folder,only an output.mbtiles file.

What am I missing?

Thanks

**Comment by wipfli** [comment]
It creates output.pmtiles in the current folder, no?

**Comment by etiennejourdier** [comment]
Hi,
It seems to me that the --output option doesn't work when using docker. I always get only the output.mbtiles file. No problem, I finally used java, but I'd rather report it here.

**Comment by msbarry** [comment]
> Hi,
> 
> It seems to me that the --output option doesn't work when using docker. I always get only the output.mbtiles file. No problem, I finally used java, but I'd rather report it here.

@etiennejourdier what docker command are you running exactly?

**Comment by etiennejourdier** [comment]
I used the one in the readme for smaller extracts plus the output option
```
docker run -e JAVA_TOOL_OPTIONS="-Xmx1g" -v "$(pwd)/data":/data ghcr.io/onthegomap/planetiler:latest --download --area=monaco \
  --water-polygons-url=https://github.com/onthegomap/planetiler/raw/main/planetiler-core/src/test/resources/water-polygons-split-3857.zip \
  --natural-earth-url=https://github.com/onthegomap/planetiler/raw/main/planetiler-core/src/test/resources/natural_earth_vector.sqlite.zip --output=monaco.pmtiles
```

**Comment by msbarry** [comment]
I think you need --output=data/output.pmtiles to get it into the mapped volume

**Comment by etiennejourdier** [comment]
Of course it seems obvious now that I'm reading it! Thanks!
